#!/bin/bash

POSITIONAL=()

while [[ $# -gt 0 ]]; do
    K="$1"

    case $K in
    -e|--execute)
        ENAME="$2"
        shift; shift
        ;;
    -l|--label)
        LABELNAME="$2"
        shift; shift
        ;;
    *)
        POSITIONAL+=("$1")
        shift
        ;;
    esac
done

set -- "${POSITIONAL[@]}"
FILENAME="$1"
touch "$FILENAME"

while true; do
    printf "\$> "
    read STDIN

    STDOUT=$($SHELL -c "$STDIN")
    echo "$STDOUT"

    echo "#COMMAND:" >> $FILENAME
    echo "$STDIN" >> $FILENAME
    echo "#OUTPUT:" >> $FILENAME
    echo "$STDOUT" | sed 's/^/#\t/' >> $FILENAME
done